# Generated by Django 3.0.4 on 2020-05-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
