# Generated by Django 3.0.4 on 2020-05-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200501_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new_groups',
        ),
    ]
