# Generated by Django 3.0.4 on 2020-05-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('account', '0023_auto_20200501_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_groups', to='auth.Group'),
        ),
    ]
