# Generated by Django 3.0.4 on 2020-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20200506_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='account.Role'),
        ),
    ]
