# Generated by Django 3.0.4 on 2020-05-06 14:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="01796580404", max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
