# Generated by Django 3.0.4 on 2020-05-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
