# Generated by Django 3.0.7 on 2020-06-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
