# Generated by Django 3.0.7 on 2020-07-06 04:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_address_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('pk',), 'verbose_name': 'Address', 'verbose_name_plural': "Address's"},
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
