# Generated by Django 3.0.7 on 2020-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20200707_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
