# Generated by Django 3.0.7 on 2020-07-07 12:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20200707_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=256, region=None),
        ),
    ]
