# Generated by Django 3.0.7 on 2020-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20200707_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='BD', max_length=256),
        ),
    ]
