# Generated by Django 3.0.7 on 2020-08-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20200729_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=256),
        ),
    ]
