# Generated by Django 3.0.7 on 2020-08-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_auto_20200822_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
