# Generated by Django 3.0.7 on 2020-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='account.CustomGroup'),
        ),
    ]
