# Generated by Django 3.0.7 on 2020-08-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_auto_20200825_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
