# Generated by Django 3.0.7 on 2020-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
