# Generated by Django 3.0.7 on 2020-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'pending'), ('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('placed', 'Placed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=32),
        ),
    ]
