# Generated by Django 3.0.7 on 2020-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200706_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=15),
            preserve_default=False,
        ),
    ]
