# Generated by Django 3.0.7 on 2020-08-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
