# Generated by Django 3.0.7 on 2020-08-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200817_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_on',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
