# Generated by Django 3.0.7 on 2020-08-17 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_auto_20200817_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='deliverycharge',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverycharge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_charge_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
