# Generated by Django 3.0.7 on 2020-08-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20200818_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='flat_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
