# Generated by Django 3.0.7 on 2020-08-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_deliverycharge_flat_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycharge',
            old_name='amount',
            new_name='delivery_charge',
        ),
    ]
