# Generated by Django 3.0.7 on 2020-08-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20200819_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='city',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattragram', 'Chattagram'), ('Khulna', 'Khulna')], default='Dhaka', max_length=100),
        ),
    ]
