# Generated by Django 3.0.7 on 2020-08-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_deliverycharge_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
