# Generated by Django 3.0.4 on 2020-04-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200419_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryManager',
        ),
    ]
