# Generated by Django 3.0.4 on 2020-05-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_parentcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentCategory',
        ),
    ]
