# Generated by Django 3.0.4 on 2020-05-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_area_atentusiano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atentusiano',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Atentusiano',
        ),
    ]
