# Generated by Django 3.0.4 on 2020-06-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200506_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_sold',
            field=models.BigIntegerField(default=0, verbose_name='Count Sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='charge_taxes',
            field=models.BooleanField(default=True, verbose_name='Charge Taxes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, max_length=128, verbose_name='Image Alt'),
        ),
    ]
