# Generated by Django 3.0.7 on 2020-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200610_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
