# Generated by Django 3.0.7 on 2020-06-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_items'),
        ('products', '0018_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(to='order.Order'),
        ),
    ]
