# Generated by Django 3.0.7 on 2020-06-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
