# Generated by Django 3.0.7 on 2020-06-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_orderitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
    ]
