# Generated by Django 3.0.7 on 2020-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_slug'),
        ('products', '0021_remove_orderitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(related_name='order_items', to='order.Order'),
        ),
    ]
