# Generated by Django 3.0.7 on 2020-08-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200709_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
